CREATE DATABASE IF NOT EXISTS voiture;

USE voiture;

CREATE TABLE (

	prenom
	PRIMARY KEY(id_voiture)
) ENGINE=InnoDB;

id_voiture VARCHAR(100) NOT NULL AUTO_INCREMENT.
marque VARCHAR(15) NOT NULL,
modele VARCHAR(15) NOT NULL,
annee INT(4) NOT NULL,
nb_porte VARCHAR(15) NOT NULL,
couleur VARCHAR(15) NOT NULL,
nb_place INT(8) NOT NULL,
